### ISSUE TITLE
P4 Edit on Save (Command-S)

### ISSUE THREAD

**Issue by trungly** [textmate/perforce.tmbundle#2]
The "Add or Edit.tmCommand" command doesn't appear to trigger when saving files with the Perforce bundle.  I've tried playing with this command in the Bundle Editor to no avail.

It does work if I set a keyEquivalent to a keyboard shortcut (even Command-S), but that seems to be only a work around, not the intended behavior.

I'm running TextMate version Version 1.5.11 (1635)

**Comment by infininight** [comment]
Note that the master branch of the bundle is designed for 2.0, make sure you are using the 1.x branch:

https://github.com/textmate/perforce.tmbundle/tree/textmate-1.x
