### ISSUE TITLE
Auto-select change description area when invoked by 'p4 change' for a new change

### ISSUE THREAD

**Issue by squatch** [textmate/perforce.tmbundle#5]
Steps to reproduce: 
1. export EDITOR=mate
2. cd into a p4 workspace with no files currently open
3. p4 edit file.txt
4. p4 change

Expected result: TextMate opens to edit the changelist specification. <enter description here> should be auto-selected so I can just start typing it.

Actual result: TextMate opens to edit the changelist specification, but the caret is positioned at the start of the file.

Environment: 
10.8.2 12C60
TextMate version 2.0-alpha.9387
Perforce bundle

**Comment by infininight** [comment]
I presume you are running all of the above commands from the command line. There isn't a way to have TextMate jump to any specific line in a file when it opens\* so this isn't possible.

You can do so with mate, so I guess you could specify a line to put the caret on for all files started with mate, and if perforce lets you set a separate EDITOR you could only set it there. That said this is a personal setting unrelated to the bundle so closing this issue.

**Comment by squatch** [comment]
> There isn't a way to have TextMate jump to any specific line in a file when it opens\* so this isn't possible.

Is there a rationale for not adding it? (Was there a footnote to go with that splat?)

> You can do so with mate, so I guess you could specify a line to put the caret on for all files started with mate, and if perforce lets you set a separate EDITOR you could only set it there. That said this is a personal setting unrelated to the bundle so closing this issue.

I could do it this way, but then no one else would get this goodness. It's just pushing the burden somewhere else, and arguably the Perforce bundle is the most appropriate place for it.
